/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package youtube;

import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class GUI extends javax.swing.JFrame {

    private String destinationDirectory = null;

    public GUI() {
        initComponents();
        setLocationRelativeTo(null);
        mp3.setActionCommand("mp3");
        mp4.setActionCommand("mp4");

    }

    int x, y;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttons = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        UrlTextField = new javax.swing.JTextField();
        PathTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        mp4 = new javax.swing.JRadioButton();
        mp3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UrlTextField.setFont(new java.awt.Font("Segoe UI Semilight", 2, 15)); // NOI18N
        UrlTextField.setText("Enter the URL");
        UrlTextField.setToolTipText("Enter the URL!");
        UrlTextField.setBorder(null);
        UrlTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UrlTextField.setName(""); // NOI18N
        UrlTextField.setOpaque(false);
        UrlTextField.setSelectionStart(0);
        UrlTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UrlTextFieldMouseClicked(evt);
            }
        });
        jPanel1.add(UrlTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 320, 30));

        PathTextField.setFont(new java.awt.Font("Segoe UI Semilight", 2, 15)); // NOI18N
        PathTextField.setText("Where do you want to save it?");
        PathTextField.setToolTipText("Enter the Path!");
        PathTextField.setBorder(null);
        PathTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PathTextField.setName(""); // NOI18N
        PathTextField.setOpaque(false);
        PathTextField.setSelectionEnd(30);
        PathTextField.setSelectionStart(0);
        PathTextField.setVerifyInputWhenFocusTarget(false);
        PathTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PathTextFieldMouseClicked(evt);
            }
        });
        jPanel1.add(PathTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 320, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/youtube/Webp.net-resizeimage (1).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 130, 360, -1));

        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, 60));

        buttons.add(mp4);
        mp4.setFont(new java.awt.Font("Javanese Text", 2, 14)); // NOI18N
        mp4.setText("Mp4");
        mp4.setBorder(null);
        mp4.setOpaque(false);
        mp4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/youtube/x.png"))); // NOI18N
        jPanel1.add(mp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 60, -1));

        buttons.add(mp3);
        mp3.setFont(new java.awt.Font("Javanese Text", 2, 14)); // NOI18N
        mp3.setText("Mp3");
        mp3.setBorder(null);
        mp3.setOpaque(false);
        mp3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/youtube/x.png"))); // NOI18N
        jPanel1.add(mp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 60, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 238, 238));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Convert");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 339, 220, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/youtube/Webp.net-resizeimage (1).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 60, 360, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/youtube/6361dfa6-f507-4838-9e34-9939641f4a6f.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 334, 230, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/youtube/x.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/youtube/6b89921c6b9f7031cfbb3c68972e1917.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Thread t = new Thread() {
            @Override
            public void run() {
                jTextField2.setText("Loading...");
            }
        };
        t.start();

        destinationDirectory = PathTextField.getText();
        if (destinationDirectory.trim().equals("")) {
            destinationDirectory = null;
        }
        if (!buttons.isSelected(null)) {
            if (buttons.getSelection().getActionCommand().equals("mp4")) {
                Youtube yt = new Youtube(
                        "C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python37-32\\Scripts\\youtube-dl --title " + UrlTextField.getText());
                moveFiles();
                jTextField2.setText("Done.\n");
            } else {
                Youtube ec = new Youtube(
                        "C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python37-32\\Scripts\\youtube-dl -x --title " + UrlTextField.getText()
                        + UrlTextField.getText());

                jTextField2.setText("Done.\n");

            }
        } else {
            JOptionPane.showMessageDialog(this, "Please check one of the check boxes!");
        }

    }//GEN-LAST:event_jLabel5MouseClicked

    private void moveFiles() {
        File currentDirectory = new File("C:\\Users\\Acer\\Documents\\NetBeansProjects\\Youtube");
        if (destinationDirectory != null) {
            if (destinationDirectory.equals("desktop")) {
                destinationDirectory = "C:\\Users\\Acer\\Desktop";
            } else if (destinationDirectory.equals("downloads")) {
                destinationDirectory = "C:\\Users\\Acer\\Downloads";
            } else if (destinationDirectory.contains("my music") || destinationDirectory.contains("myMusic")) {
                destinationDirectory = "C:\\Users\\Acer\\Desktop\\MyMusic";
            }
            File destinationDirectory = new File(this.destinationDirectory);
            String[] files = currentDirectory.list();
            for (int i = 0; i < files.length; i++) {
                if (files[i].endsWith("mp4") || files[i].endsWith("webm") || files[i].endsWith("m4a")) {
                    File file = new File(files[i]);
                    file.renameTo(new File(destinationDirectory + "\\" + file.getName()));
                }
            }
        }

    }
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        jTextField2.setText("");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void PathTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PathTextFieldMouseClicked
        PathTextField.setText("");
    }//GEN-LAST:event_PathTextFieldMouseClicked

    private void UrlTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UrlTextFieldMouseClicked
        UrlTextField.setText("");
    }//GEN-LAST:event_UrlTextFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PathTextField;
    private javax.swing.JTextField UrlTextField;
    private javax.swing.ButtonGroup buttons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton mp3;
    private javax.swing.JRadioButton mp4;
    // End of variables declaration//GEN-END:variables
}
